name: 部署到GitHub Pages

on:
  push:
    branches: [ "master" ]
  # 允许手动触发工作流
  workflow_dispatch:

# 设置GITHUB_TOKEN的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      
      - name: 设置Pages
        uses: actions/configure-pages@v4
        
      - name: 上传文件
        uses: actions/upload-pages-artifact@v2
        with:
          # 上传整个仓库
          path: '.'
          
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3 